# Generated by Django 4.0.3 on 2022-04-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название фильма')),
                ('movie_image', models.ImageField(upload_to='', verbose_name='Обложка фильма')),
                ('rating', models.FloatField(verbose_name='Рейтинг фильма')),
                ('genre', models.CharField(max_length=255, verbose_name='Жанр')),
                ('description', models.TextField(verbose_name='Описание фильма')),
            ],
        ),
    ]
